packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.42.0
  "@platforma-sdk/ui-vue": ^1.42.0
  "@platforma-sdk/workflow-tengo": ^4.8.0
  "@platforma-sdk/block-tools": ^2.5.57
  "@platforma-sdk/test": ^1.42.0
  "@platforma-sdk/tengo-builder": ^2.1.10
  "@platforma-sdk/package-builder": ^2.16.0
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/ts-builder": ^1.0.0
  "@milaboratories/ts-configs": ^1.0.0
  "@milaboratories/build-configs": ^1.0.0
  "@milaboratories/pl-model-common": ^1.19.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "typescript": ~5.5.4
  "turbo": ^2.5.4

  "vue": ^3.5.18
  "@vueuse/core": ^13.6.0
  "vitest": ~2.1.9
  "csv-parse": ^6.1.0
  "es-toolkit": ^1.39.0

  "@changesets/cli": ^2.29.5
  "js-yaml": "^4.1.0"
